### PR TITLE
Add video import wizard

### PR DESCRIPTION
**Pull request by abias**
This PR mainly adds an import wizard to the Opencast videos overviews page which lets teachers import videos from other courses which they have access to.

However, while working on the patch, I changed some things in the existing backup & restore mechanism as well as other minor things which didn't make sense to be split into individual PRs.

I tried my best to write good commit messages which explain all changes and which reveal you my train of thought.

If you have any questions or change requests, please raise them.

Note 1: This change does not have Behat coverage yet. This would have been slightly more work as I have time currently. I hope that this is not a show-stopper. At least I can tell then this code has been running for 3 weeks in production here without any problems up to now.

Note 2: We have german translations ready for the added / modified strings and are ready to contribute these to AMOS as soon as this patch is merged and published in the plugin repo.

Cheers,
Alex

### CODE REVIEW

**Comment by abias** [comment]
I rebased this PR to the latest master to turn it mergable again.

**Comment by moodlebeuth** [comment]
Hello @abias, Hello @NinaHerrmann,
I have tested the PR of Alex in our test environment and it works as expected.
Thanks & Greetings,
Michael

**Comment by moodlebeuth** [comment]
I would be grateful if this PR could be merged before the next summer term.

**Comment by TamaraGunkel** [comment]
Hi,
@abias thanks for the great work and @moodlebeuth for reviewing!
Sorry for the delay. I (finally) merged your PR and I will also create a new release soon.

**Comment by abias** [comment]
@TamaraGunkel As promised, I just added the german translation for the strings which have been added (and released) within this PR to AMOS. They are just waiting for review by the language pack maintainers and should then be merged soon.

**Pull request merged**
