### PR TITLE
some basic codestyling things

### PR DESCRIPTION
**Pull request by NinaHerrmann**
Two major style changes have been introduced in the Pull Request:
- change the order of strings to alphabetically
- move `require_once('../../config.php');` after the use statements as, for some reason, the other order does not find the @copyright and @licence tags. 

Some minor changes, such as not exceeding 135 Characters per line, are also part of this pull request. 
Adjusted batchupload_setting_desc to describe the feature not available in detail.

### CODE REVIEW

**Comment by NinaHerrmann** [comment]
Fixes #380

**Comment by ferishili** [comment]
Hi @NinaHerrmann
it seems that the latest changes are not compatible with the behat feature test for` direct access`, would you please take a look at that?

**Comment by ferishili** [comment]
due to an unexpected behavior from `directaccess` behat feature, it has been disabled in this PR

**Review by ferishili — COMMENTED** [review]
lgtm

**Pull request merged**
