### PR TITLE
Urlencode filename in download Content-Disposition response header

### PR DESCRIPTION
**Pull request by justusdieckmann**

### CODE REVIEW

**Comment by justusdieckmann** [comment]
CI is failing on master because update/40 is not yet merged, but no actual issues

**Comment by ferishili** [comment]
Hi @justusdieckmann,
Thanks for your contribution, please rebase this PR

**Comment by NinaHerrmann** [comment]
@ferishili as https://github.com/Opencast-Moodle/moodle-tool_opencast/pull/51 was kind of "unnecessary" work, (you pushed own commits for improving CI) will you even merge this?

**Comment by ferishili** [comment]
Hi @NinaHerrmann,
The CI is fixed now, and this PR has nothing to do with https://github.com/Opencast-Moodle/moodle-tool_opencast/pull/51.
The rebase would pass the CI checks and I think merging this would improve the downloading with a bit of trick which I will add later on.

**Comment by NinaHerrmann** [comment]
Hey @ferishili 
I think you understood me wrong. This pull request is only meaningful if it is merged. As the other one was not merged, I would prefer to know if you even want to integrate it to avoid additional work.

**Pull request merged**
